// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// Diese Übersetzung wurde von einer KI generiert. Falls eine Formulierung unnatürlich klingt, freuen wir uns über Korrekturvorschläge.
import type { TranslationDict } from "./en.js";

export const de = {
    // ExportPage
    format: "Format",
    platform: "Plattform",
    tooltipQuality: "Komprimierungsqualität einstellen (1-100%)",
    tooltipScale: "Exportmaßstab einstellen (0.5-4x)",
    tooltipPrefix: "Allen exportierten Dateinamen ein Präfix hinzufügen",
    tooltipSuffix: "Allen exportierten Dateinamen ein Suffix hinzufügen",
    prefix: "Präfix",
    suffix: "Suffix",
    settings: "Einstellungen",
    exporting: "Exportieren...",
    export: "Exportieren",

    // SettingsPage
    settingsTitle: "Einstellungen",
    configuringGlobal: "Globale Einstellungen für alle Projekte konfigurieren",
    configuringProject: "Einstellungen nur für dieses Projekt konfigurieren",
    appearance: "Erscheinungsbild",
    light: "Hell",
    dark: "Dunkel",
    system: "System",
    language: "Sprache",
    layoutSettings: "Layout-Einstellungen",
    gridView: "Rasteransicht",
    listView: "Listenansicht",
    itemsPerRow: "Elemente pro Reihe:",
    actions: "Aktionen",
    autoCloseAfterExport: "Nach dem Export automatisch schließen",
    reloadPreviewOnSelectionChange: "Vorschau bei Auswahländerung neu laden",
    forceCompressionAt100Quality: "Komprimierung bei 100% Qualität erzwingen",
    previewNameCase: "Schreibweise des Vorschaunamens",
    original: "Original",
    lowercase: "Kleinbuchstaben",
    uppercase: "Großbuchstaben",
    previewNameCleanupRules: "Bereinigungsregeln für Vorschaunamen",
    exportNameCleanupRules: "Bereinigungsregeln für Exportnamen",
    addRule: "Regel hinzufügen",
    find: "Suchen",
    replaceWith: "Ersetzen durch",
    supportUs: "Uns unterstützen",
    cancel: "Abbrechen",
    save: "Speichern",
    project: "Projekt",
    global: "Global",

    // UI error messages
    errorSelectLayer: "Bitte einen Layer auswählen",
    errorEnterFileNames: "Bitte Bilddateinamen eingeben",
    errorDuplicateFileNames: "Doppelte Bilddateinamen gefunden",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : Export erfolgreich",
    notifyCompressed: "{count} Bild(er) komprimiert, {saved} gespart ({pct}%)",
} satisfies TranslationDict;
