// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// Esta traducción fue generada por IA. Si alguna expresión le parece poco natural, no dude en sugerir correcciones.
import type { TranslationDict } from "./en.js";

export const es419 = {
    // ExportPage
    format: "Formato",
    platform: "Plataforma",
    tooltipQuality: "Establecer calidad de compresión (1-100%)",
    tooltipScale: "Establecer escala de exportación (0.5-4x)",
    tooltipPrefix: "Agregar un prefijo a todos los nombres de archivo exportados",
    tooltipSuffix: "Agregar un sufijo a todos los nombres de archivo exportados",
    prefix: "Prefijo",
    suffix: "Sufijo",
    settings: "Configuración",
    exporting: "Exportando...",
    export: "Exportar",

    // SettingsPage
    settingsTitle: "Configuración",
    configuringGlobal: "Configurando ajustes globales para todos los proyectos",
    configuringProject: "Configurando ajustes solo para este proyecto",
    appearance: "Apariencia",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    language: "Idioma",
    layoutSettings: "Ajustes de diseño",
    gridView: "Vista de cuadrícula",
    listView: "Vista de lista",
    itemsPerRow: "Elementos por fila:",
    actions: "Acciones",
    autoCloseAfterExport: "Cerrar automáticamente al exportar",
    reloadPreviewOnSelectionChange: "Recargar vista previa al cambiar selección",
    forceCompressionAt100Quality: "Forzar compresión al 100% de calidad",
    previewNameCase: "Formato del nombre de vista previa",
    original: "Original",
    lowercase: "Minúsculas",
    uppercase: "Mayúsculas",
    previewNameCleanupRules: "Reglas de limpieza del nombre de vista previa",
    exportNameCleanupRules: "Reglas de limpieza del nombre de exportación",
    addRule: "Agregar regla",
    find: "Buscar",
    replaceWith: "Reemplazar con",
    supportUs: "Apóyanos",
    cancel: "Cancelar",
    save: "Guardar",
    project: "Proyecto",
    global: "Global",

    // UI error messages
    errorSelectLayer: "Por favor, selecciona una capa",
    errorEnterFileNames: "Por favor, ingresa los nombres de los archivos de imagen",
    errorDuplicateFileNames: "Se encontraron nombres de archivo de imagen duplicados",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : Exportación exitosa",
    notifyCompressed: "{count} imagen(es) comprimida(s), {saved} ahorrados ({pct}%)",
} satisfies TranslationDict;
