// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// Cette traduction a été générée par IA. Si une formulation vous semble incorrecte, n'hésitez pas à proposer des corrections.
import type { TranslationDict } from "./en.js";

export const fr = {
    // ExportPage
    format: "Format",
    platform: "Plateforme",
    tooltipQuality: "Définir la qualité de compression (1-100%)",
    tooltipScale: "Définir l'échelle d'export (0.5-4x)",
    tooltipPrefix: "Ajouter un préfixe à tous les noms de fichiers exportés",
    tooltipSuffix: "Ajouter un suffixe à tous les noms de fichiers exportés",
    prefix: "Préfixe",
    suffix: "Suffixe",
    settings: "Paramètres",
    exporting: "Export en cours...",
    export: "Exporter",

    // SettingsPage
    settingsTitle: "Paramètres",
    configuringGlobal: "Configuration des paramètres globaux pour tous les projets",
    configuringProject: "Configuration des paramètres pour ce projet uniquement",
    appearance: "Apparence",
    light: "Clair",
    dark: "Sombre",
    system: "Système",
    language: "Langue",
    layoutSettings: "Paramètres de mise en page",
    gridView: "Vue grille",
    listView: "Vue liste",
    itemsPerRow: "Éléments par ligne :",
    actions: "Actions",
    autoCloseAfterExport: "Fermer automatiquement après l'export",
    reloadPreviewOnSelectionChange: "Actualiser l'aperçu lors du changement de sélection",
    forceCompressionAt100Quality: "Forcer la compression à 100% de qualité",
    previewNameCase: "Casse du nom d'aperçu",
    original: "Original",
    lowercase: "Minuscules",
    uppercase: "Majuscules",
    previewNameCleanupRules: "Règles de nettoyage du nom d'aperçu",
    exportNameCleanupRules: "Règles de nettoyage du nom d'export",
    addRule: "Ajouter une règle",
    find: "Rechercher",
    replaceWith: "Remplacer par",
    supportUs: "Nous soutenir",
    cancel: "Annuler",
    save: "Enregistrer",
    project: "Projet",
    global: "Global",

    // UI error messages
    errorSelectLayer: "Veuillez sélectionner un calque",
    errorEnterFileNames: "Veuillez entrer les noms des fichiers image",
    errorDuplicateFileNames: "Des noms de fichiers image en double ont été trouvés",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : Export réussi",
    notifyCompressed: "{count} image(s) compressée(s), {saved} économisés ({pct}%)",
} satisfies TranslationDict;
