// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// この翻訳はAIによって生成されました。不自然な表現があればお気軽に修正をご提案ください。
import type { TranslationDict } from "./en.js";

export const ja = {
    // ExportPage
    format: "フォーマット",
    platform: "プラットフォーム",
    tooltipQuality: "圧縮品質を設定 (1-100%)",
    tooltipScale: "エクスポートスケールを設定 (0.5-4x)",
    tooltipPrefix: "すべてのファイル名にプレフィックスを追加",
    tooltipSuffix: "すべてのファイル名にサフィックスを追加",
    prefix: "プレフィックス",
    suffix: "サフィックス",
    settings: "設定",
    exporting: "エクスポート中...",
    export: "エクスポート",

    // SettingsPage
    settingsTitle: "設定",
    configuringGlobal: "すべてのプロジェクトに適用されるグローバル設定",
    configuringProject: "このプロジェクトのみに適用される設定",
    appearance: "外観",
    light: "ライト",
    dark: "ダーク",
    system: "システム",
    language: "言語",
    layoutSettings: "レイアウト設定",
    gridView: "グリッドビュー",
    listView: "リストビュー",
    itemsPerRow: "1行あたりの項目数:",
    actions: "アクション",
    autoCloseAfterExport: "エクスポート後に自動で閉じる",
    reloadPreviewOnSelectionChange: "選択変更時にプレビューを更新",
    forceCompressionAt100Quality: "100%品質でも強制圧縮",
    previewNameCase: "プレビュー名の形式",
    original: "そのまま",
    lowercase: "小文字",
    uppercase: "大文字",
    previewNameCleanupRules: "プレビュー名のクリーンアップルール",
    exportNameCleanupRules: "エクスポート名のクリーンアップルール",
    addRule: "ルールを追加",
    find: "検索",
    replaceWith: "置換",
    supportUs: "サポートする",
    cancel: "キャンセル",
    save: "保存",
    project: "プロジェクト",
    global: "グローバル",

    // UI error messages
    errorSelectLayer: "レイヤーを選択してください",
    errorEnterFileNames: "画像ファイル名を入力してください",
    errorDuplicateFileNames: "重複した画像ファイル名があります",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : エクスポート成功",
    notifyCompressed: "{count}枚の画像を圧縮、{saved}節約 ({pct}%)",
} satisfies TranslationDict;
