// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// 이 번역은 AI에 의해 생성되었습니다. 어색한 표현이 있다면 언제든지 수정을 제안해 주세요.
import type { TranslationDict } from "./en.js";

export const ko = {
    // ExportPage
    format: "형식",
    platform: "플랫폼",
    tooltipQuality: "압축 품질 설정 (1-100%)",
    tooltipScale: "내보내기 배율 설정 (0.5-4x)",
    tooltipPrefix: "내보낼 파일 이름에 접두사 추가",
    tooltipSuffix: "내보낼 파일 이름에 접미사 추가",
    prefix: "접두사",
    suffix: "접미사",
    settings: "설정",
    exporting: "내보내는 중...",
    export: "내보내기",

    // SettingsPage
    settingsTitle: "설정",
    configuringGlobal: "모든 프로젝트에 적용되는 전역 설정",
    configuringProject: "이 프로젝트에만 적용되는 설정",
    appearance: "외관",
    light: "라이트",
    dark: "다크",
    system: "시스템",
    language: "언어",
    layoutSettings: "레이아웃 설정",
    gridView: "그리드 뷰",
    listView: "리스트 뷰",
    itemsPerRow: "행당 항목:",
    actions: "동작",
    autoCloseAfterExport: "내보내기 후 자동 닫기",
    reloadPreviewOnSelectionChange: "선택 변경 시 미리보기 새로고침",
    forceCompressionAt100Quality: "100% 품질에서 강제 압축",
    previewNameCase: "미리보기 이름 형식",
    original: "원본",
    lowercase: "소문자",
    uppercase: "대문자",
    previewNameCleanupRules: "미리보기 이름 정리 규칙",
    exportNameCleanupRules: "내보내기 이름 정리 규칙",
    addRule: "규칙 추가",
    find: "찾기",
    replaceWith: "바꾸기",
    supportUs: "후원하기",
    cancel: "취소",
    save: "저장",
    project: "프로젝트",
    global: "전역",

    // UI error messages
    errorSelectLayer: "레이어를 선택해주세요",
    errorEnterFileNames: "이미지 파일 이름을 입력해주세요",
    errorDuplicateFileNames: "중복된 이미지 파일 이름이 있습니다",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : 내보내기 성공",
    notifyCompressed: "{count}개 이미지 압축, {saved} 절약 ({pct}%)",
} satisfies TranslationDict;
