// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// Esta tradução foi gerada por IA. Se alguma expressão parecer estranha, sinta-se à vontade para sugerir correções.
import type { TranslationDict } from "./en.js";

export const ptBR = {
    // ExportPage
    format: "Formato",
    platform: "Plataforma",
    tooltipQuality: "Definir qualidade de compressão (1-100%)",
    tooltipScale: "Definir escala de exportação (0.5-4x)",
    tooltipPrefix: "Adicionar um prefixo a todos os nomes de arquivo exportados",
    tooltipSuffix: "Adicionar um sufixo a todos os nomes de arquivo exportados",
    prefix: "Prefixo",
    suffix: "Sufixo",
    settings: "Configurações",
    exporting: "Exportando...",
    export: "Exportar",

    // SettingsPage
    settingsTitle: "Configurações",
    configuringGlobal: "Configurando ajustes globais para todos os projetos",
    configuringProject: "Configurando ajustes somente para este projeto",
    appearance: "Aparência",
    light: "Claro",
    dark: "Escuro",
    system: "Sistema",
    language: "Idioma",
    layoutSettings: "Ajustes de layout",
    gridView: "Visualização em grade",
    listView: "Visualização em lista",
    itemsPerRow: "Itens por linha:",
    actions: "Ações",
    autoCloseAfterExport: "Fechar automaticamente após exportar",
    reloadPreviewOnSelectionChange: "Recarregar prévia ao mudar seleção",
    forceCompressionAt100Quality: "Forçar compressão a 100% de qualidade",
    previewNameCase: "Formato do nome da prévia",
    original: "Original",
    lowercase: "Minúsculas",
    uppercase: "Maiúsculas",
    previewNameCleanupRules: "Regras de limpeza do nome da prévia",
    exportNameCleanupRules: "Regras de limpeza do nome de exportação",
    addRule: "Adicionar regra",
    find: "Localizar",
    replaceWith: "Substituir por",
    supportUs: "Apoie-nos",
    cancel: "Cancelar",
    save: "Salvar",
    project: "Projeto",
    global: "Global",

    // UI error messages
    errorSelectLayer: "Por favor, selecione uma camada",
    errorEnterFileNames: "Por favor, insira os nomes dos arquivos de imagem",
    errorDuplicateFileNames: "Nomes de arquivos de imagem duplicados encontrados",

    // Plugin notify messages
    notifySuccess: "Figma Exporter : Exportação concluída",
    notifyCompressed: "{count} imagem(ns) comprimida(s), {saved} economizados ({pct}%)",
} satisfies TranslationDict;
