// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// 此翻译由AI生成。如有任何表达不自然之处，欢迎提出修改建议。
import type { TranslationDict } from "./en.js";

export const zhCN = {
    // ExportPage
    format: "格式",
    platform: "平台",
    tooltipQuality: "设置压缩质量 (1-100%)",
    tooltipScale: "设置导出缩放比例 (0.5-4x)",
    tooltipPrefix: "为所有导出文件名添加前缀",
    tooltipSuffix: "为所有导出文件名添加后缀",
    prefix: "前缀",
    suffix: "后缀",
    settings: "设置",
    exporting: "导出中...",
    export: "导出",

    // SettingsPage
    settingsTitle: "设置",
    configuringGlobal: "配置所有项目的全局设置",
    configuringProject: "仅配置此项目的设置",
    appearance: "外观",
    light: "浅色",
    dark: "深色",
    system: "跟随系统",
    language: "语言",
    layoutSettings: "布局设置",
    gridView: "网格视图",
    listView: "列表视图",
    itemsPerRow: "每行项目数：",
    actions: "操作",
    autoCloseAfterExport: "导出后自动关闭",
    reloadPreviewOnSelectionChange: "选择更改时刷新预览",
    forceCompressionAt100Quality: "100% 质量时强制压缩",
    previewNameCase: "预览名称格式",
    original: "原始",
    lowercase: "小写",
    uppercase: "大写",
    previewNameCleanupRules: "预览名称清理规则",
    exportNameCleanupRules: "导出名称清理规则",
    addRule: "添加规则",
    find: "查找",
    replaceWith: "替换为",
    supportUs: "支持我们",
    cancel: "取消",
    save: "保存",
    project: "项目",
    global: "全局",

    // UI error messages
    errorSelectLayer: "请选择一个图层",
    errorEnterFileNames: "请输入图片文件名",
    errorDuplicateFileNames: "发现重复的图片文件名",

    // Plugin notify messages
    notifySuccess: "Figma Exporter：导出成功",
    notifyCompressed: "已压缩 {count} 张图片，节省 {saved}（{pct}%）",
} satisfies TranslationDict;
