// This translation was generated by AI. If any phrasing sounds unnatural, please feel free to suggest corrections.
// 此翻譯由AI生成。如有任何表達不自然之處，歡迎提出修改建議。
import type { TranslationDict } from "./en.js";

export const zhTW = {
    // ExportPage
    format: "格式",
    platform: "平台",
    tooltipQuality: "設定壓縮品質 (1-100%)",
    tooltipScale: "設定匯出縮放比例 (0.5-4x)",
    tooltipPrefix: "為所有匯出檔案名稱新增前綴",
    tooltipSuffix: "為所有匯出檔案名稱新增後綴",
    prefix: "前綴",
    suffix: "後綴",
    settings: "設定",
    exporting: "匯出中...",
    export: "匯出",

    // SettingsPage
    settingsTitle: "設定",
    configuringGlobal: "設定所有專案的全域設定",
    configuringProject: "僅設定此專案的設定",
    appearance: "外觀",
    light: "淺色",
    dark: "深色",
    system: "跟隨系統",
    language: "語言",
    layoutSettings: "版面設定",
    gridView: "格狀檢視",
    listView: "清單檢視",
    itemsPerRow: "每列項目數：",
    actions: "動作",
    autoCloseAfterExport: "匯出後自動關閉",
    reloadPreviewOnSelectionChange: "選取變更時重新載入預覽",
    forceCompressionAt100Quality: "100% 品質時強制壓縮",
    previewNameCase: "預覽名稱格式",
    original: "原始",
    lowercase: "小寫",
    uppercase: "大寫",
    previewNameCleanupRules: "預覽名稱清理規則",
    exportNameCleanupRules: "匯出名稱清理規則",
    addRule: "新增規則",
    find: "尋找",
    replaceWith: "取代為",
    supportUs: "支持我們",
    cancel: "取消",
    save: "儲存",
    project: "專案",
    global: "全域",

    // UI error messages
    errorSelectLayer: "請選取一個圖層",
    errorEnterFileNames: "請輸入圖片檔案名稱",
    errorDuplicateFileNames: "發現重複的圖片檔案名稱",

    // Plugin notify messages
    notifySuccess: "Figma Exporter：匯出成功",
    notifyCompressed: "已壓縮 {count} 張圖片，節省 {saved}（{pct}%）",
} satisfies TranslationDict;
